remote_theme: just-the-docs/just-the-docs
nav_external_links:
  - title: Documentation
    url: https://vimms.readthedocs.io
  - title: Demonstration codes
    url: https://github.com/glasgowcompbio/vimms/tree/master/demo
  - title: Codes for papers
    url: https://github.com/glasgowcompbio/vimms/tree/master/examples
