name: vimms
channels:
- defaults
dependencies:
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - plotly
  - scikit-learn
  - tqdm
  - joblib
  - ipyparallel
  - requests
  - loguru
  - networkx
  - jsonpickle
  - statsmodels
  - tabulate
  - flake8
  - autopep8
  - pytest
  - pytest-cov
  - intervaltree
  - jupyterlab
  - ipywidgets
  - pip
  - pip:
    - events
    - gpy
    - mkdocs
    - mkdocstrings
    - pymzml==2.4.7
    - psims
    - mass-spec-utils
    - pysmiles
