# mkdocs.yml
site_name: Virtual Metabolomics Mass Spectrometry (ViMMS)
theme:
  name: "readthedocs"

plugins:
- search
- mkdocstrings:
    handlers:
        python:
            setup_commands:
                - import sys
                - sys.path.append('../')
            selection:
                new_path_syntax: true

nav:
  - Home: README.md
  - Creating Chemicals: chemicals.md
  - Running Controllers: controllers.md
  - API Documentation:
    - Common: api/common.md
    - Chemical Generation Process:
        - Chemicals: api/chemicals.md
        - Chemical Samplers: api/chemical_samplers.md
        - ROI: api/roi.md
        - Box: api/box.md
    - Mass Spectrometry Process:
        - Mass Spec: api/mass_spec.md
        - Column: api/column.md
        - Noise: api/noise.md
    - Fragmentation Strategy Simulation Process:
        - Environment: api/environment.md
        - Controllers: api/controllers.md
        - Dynamic Exclusion: api/exclusion.md
        - Agents: api/agent.md
    - Others:
        - Feature Extractions: api/feature_extractions.md
        - MzMLWriter: api/mzml_writer.md