# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ExperimentPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_experimentForm(object):
    def setupUi(self, experimentForm):
        experimentForm.setObjectName("experimentForm")
        experimentForm.resize(600, 500)
        self.VisualiseTitleLabel = QtWidgets.QLabel(experimentForm)
        self.VisualiseTitleLabel.setGeometry(QtCore.QRect(0, 0, 600, 100))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.VisualiseTitleLabel.setFont(font)
        self.VisualiseTitleLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.VisualiseTitleLabel.setObjectName("VisualiseTitleLabel")
        self.ExperimentHomeButton = QtWidgets.QPushButton(experimentForm)
        self.ExperimentHomeButton.setGeometry(QtCore.QRect(540, 20, 50, 50))
        self.ExperimentHomeButton.setText("")
        self.ExperimentHomeButton.setObjectName("ExperimentHomeButton")
        self.FullscanGroupBox = QtWidgets.QGroupBox(experimentForm)
        self.FullscanGroupBox.setGeometry(QtCore.QRect(0, 100, 290, 211))
        self.FullscanGroupBox.setTitle("")
        self.FullscanGroupBox.setObjectName("FullscanGroupBox")
        self.FullscanSelectLabel = QtWidgets.QLabel(self.FullscanGroupBox)
        self.FullscanSelectLabel.setGeometry(QtCore.QRect(10, 5, 225, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FullscanSelectLabel.setFont(font)
        self.FullscanSelectLabel.setObjectName("FullscanSelectLabel")
        self.SelectedFullscanLabel = QtWidgets.QLabel(self.FullscanGroupBox)
        self.SelectedFullscanLabel.setGeometry(QtCore.QRect(10, 120, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SelectedFullscanLabel.setFont(font)
        self.SelectedFullscanLabel.setObjectName("SelectedFullscanLabel")
        self.FullscanNamesLabel = QtWidgets.QLabel(self.FullscanGroupBox)
        self.FullscanNamesLabel.setGeometry(QtCore.QRect(10, 140, 270, 61))
        self.FullscanNamesLabel.setStyleSheet("font-weight: bold;")
        self.FullscanNamesLabel.setText("")
        self.FullscanNamesLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.FullscanNamesLabel.setObjectName("FullscanNamesLabel")
        self.NoOfInjectionsLabel = QtWidgets.QLabel(self.FullscanGroupBox)
        self.NoOfInjectionsLabel.setGeometry(QtCore.QRect(10, 65, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NoOfInjectionsLabel.setFont(font)
        self.NoOfInjectionsLabel.setObjectName("NoOfInjectionsLabel")
        self.NoOfInjectionsSpinBox = QtWidgets.QSpinBox(self.FullscanGroupBox)
        self.NoOfInjectionsSpinBox.setGeometry(QtCore.QRect(160, 65, 42, 22))
        self.NoOfInjectionsSpinBox.setMinimum(1)
        self.NoOfInjectionsSpinBox.setMaximum(15)
        self.NoOfInjectionsSpinBox.setObjectName("NoOfInjectionsSpinBox")
        self.AddFullscanButton = QtWidgets.QPushButton(self.FullscanGroupBox)
        self.AddFullscanButton.setGeometry(QtCore.QRect(10, 90, 75, 23))
        self.AddFullscanButton.setObjectName("AddFullscanButton")

        self.retranslateUi(experimentForm)
        QtCore.QMetaObject.connectSlotsByName(experimentForm)

    def retranslateUi(self, experimentForm):
        _translate = QtCore.QCoreApplication.translate
        experimentForm.setWindowTitle(_translate("experimentForm", "Form"))
        self.VisualiseTitleLabel.setText(_translate("experimentForm", "Experiment"))
        self.FullscanSelectLabel.setText(_translate("experimentForm", "Please select fullscans to inject:"))
        self.SelectedFullscanLabel.setText(_translate("experimentForm", "Selected fullscan injections:"))
        self.NoOfInjectionsLabel.setText(_translate("experimentForm", "# of times to inject:"))
        self.AddFullscanButton.setText(_translate("experimentForm", "Add"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    experimentForm = QtWidgets.QWidget()
    ui = Ui_experimentForm()
    ui.setupUi(experimentForm)
    experimentForm.show()
    sys.exit(app.exec_())
