# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ExtractGeneratePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExtractGenerateForm(object):
    def setupUi(self, ExtractGenerateForm):
        ExtractGenerateForm.setObjectName("ExtractGenerateForm")
        ExtractGenerateForm.resize(600, 500)
        self.ExtractTitleLabel = QtWidgets.QLabel(ExtractGenerateForm)
        self.ExtractTitleLabel.setGeometry(QtCore.QRect(0, 0, 600, 100))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.ExtractTitleLabel.setFont(font)
        self.ExtractTitleLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ExtractTitleLabel.setObjectName("ExtractTitleLabel")
        self.ExtractGenerateButton = QtWidgets.QPushButton(ExtractGenerateForm)
        self.ExtractGenerateButton.setGeometry(QtCore.QRect(100, 200, 400, 75))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ExtractGenerateButton.setFont(font)
        self.ExtractGenerateButton.setObjectName("ExtractGenerateButton")
        self.ExperimenButton = QtWidgets.QPushButton(ExtractGenerateForm)
        self.ExperimenButton.setGeometry(QtCore.QRect(100, 300, 400, 75))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ExperimenButton.setFont(font)
        self.ExperimenButton.setObjectName("ExperimenButton")
        self.VisualiseButton = QtWidgets.QPushButton(ExtractGenerateForm)
        self.VisualiseButton.setGeometry(QtCore.QRect(100, 400, 400, 75))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.VisualiseButton.setFont(font)
        self.VisualiseButton.setObjectName("VisualiseButton")
        self.tabWidget = QtWidgets.QTabWidget(ExtractGenerateForm)
        self.tabWidget.setGeometry(QtCore.QRect(0, 100, 600, 400))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.SelectFileDesc = QtWidgets.QLabel(self.tab)
        self.SelectFileDesc.setGeometry(QtCore.QRect(0, 30, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SelectFileDesc.setFont(font)
        self.SelectFileDesc.setObjectName("SelectFileDesc")
        self.SelectFileButton = QtWidgets.QToolButton(self.tab)
        self.SelectFileButton.setGeometry(QtCore.QRect(200, 30, 23, 20))
        self.SelectFileButton.setObjectName("SelectFileButton")
        self.ExtractFileNameLabel = QtWidgets.QLabel(self.tab)
        self.ExtractFileNameLabel.setGeometry(QtCore.QRect(230, 30, 350, 14))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExtractFileNameLabel.sizePolicy().hasHeightForWidth())
        self.ExtractFileNameLabel.setSizePolicy(sizePolicy)
        self.ExtractFileNameLabel.setObjectName("ExtractFileNameLabel")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.ExtractHomeButton = QtWidgets.QPushButton(ExtractGenerateForm)
        self.ExtractHomeButton.setGeometry(QtCore.QRect(540, 20, 50, 50))
        self.ExtractHomeButton.setText("")
        self.ExtractHomeButton.setObjectName("ExtractHomeButton")

        self.retranslateUi(ExtractGenerateForm)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ExtractGenerateForm)

    def retranslateUi(self, ExtractGenerateForm):
        _translate = QtCore.QCoreApplication.translate
        ExtractGenerateForm.setWindowTitle(_translate("ExtractGenerateForm", "Form"))
        self.ExtractTitleLabel.setText(_translate("ExtractGenerateForm", "Extract/Generate Data"))
        self.ExtractGenerateButton.setText(_translate("ExtractGenerateForm", "Extract/Generate Data"))
        self.ExperimenButton.setText(_translate("ExtractGenerateForm", "Simulate Experiment"))
        self.VisualiseButton.setText(_translate("ExtractGenerateForm", "Visualise Results"))
        self.SelectFileDesc.setText(_translate("ExtractGenerateForm", "Please Select an .mzML file:"))
        self.SelectFileButton.setText(_translate("ExtractGenerateForm", "..."))
        self.ExtractFileNameLabel.setText(_translate("ExtractGenerateForm", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ExtractGenerateForm", "Extract"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ExtractGenerateForm", "Generate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ExtractGenerateForm = QtWidgets.QWidget()
    ui = Ui_ExtractGenerateForm()
    ui.setupUi(ExtractGenerateForm)
    ExtractGenerateForm.show()
    sys.exit(app.exec_())
