# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StartPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1200, 900)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.homePageTitleLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(86)
        self.homePageTitleLabel.setFont(font)
        self.homePageTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.homePageTitleLabel.setObjectName("homePageTitleLabel")
        self.verticalLayout.addWidget(self.homePageTitleLabel)
        self.DescriptionLabel = QtWidgets.QLabel(Form)
        self.DescriptionLabel.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setItalic(True)
        self.DescriptionLabel.setFont(font)
        self.DescriptionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.DescriptionLabel.setObjectName("DescriptionLabel")
        self.verticalLayout.addWidget(self.DescriptionLabel)
        self.ExtractGenerateButton = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.ExtractGenerateButton.setFont(font)
        self.ExtractGenerateButton.setObjectName("ExtractGenerateButton")
        self.verticalLayout.addWidget(self.ExtractGenerateButton)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "ViMMS Visualised"))
        self.homePageTitleLabel.setText(_translate("Form", "ViMMS Visualised"))
        self.DescriptionLabel.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Vi</span>rtual <span style=\" font-weight:600;\">M</span>etabolomics <span style=\" font-weight:600;\">M</span>ass <span style=\" font-weight:600;\">S</span>pectrometer</p></body></html>"))
        self.ExtractGenerateButton.setText(_translate("Form", "Extract/Generate \n"
"Data"))
        self.pushButton_2.setText(_translate("Form", "Simulate\n"
"Experiment"))
        self.pushButton_3.setText(_translate("Form", "Visualise/Evaluate\n"
"Results"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
