# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StartPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 500)
        self.TitleLabel = QtWidgets.QLabel(Form)
        self.TitleLabel.setGeometry(QtCore.QRect(0, 0, 600, 125))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.TitleLabel.setFont(font)
        self.TitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TitleLabel.setObjectName("TitleLabel")
        self.SubHeadingLabel = QtWidgets.QLabel(Form)
        self.SubHeadingLabel.setGeometry(QtCore.QRect(0, 125, 600, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.SubHeadingLabel.setFont(font)
        self.SubHeadingLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.SubHeadingLabel.setObjectName("SubHeadingLabel")
        self.ExtractGenerateButton = QtWidgets.QPushButton(Form)
        self.ExtractGenerateButton.setGeometry(QtCore.QRect(150, 170, 300, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ExtractGenerateButton.setFont(font)
        self.ExtractGenerateButton.setObjectName("ExtractGenerateButton")
        self.SimulateButton = QtWidgets.QPushButton(Form)
        self.SimulateButton.setGeometry(QtCore.QRect(150, 250, 300, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SimulateButton.setFont(font)
        self.SimulateButton.setObjectName("SimulateButton")
        self.VisualiseButton = QtWidgets.QPushButton(Form)
        self.VisualiseButton.setGeometry(QtCore.QRect(150, 330, 300, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.VisualiseButton.setFont(font)
        self.VisualiseButton.setObjectName("VisualiseButton")
        self.ExperimentButton = QtWidgets.QPushButton(Form)
        self.ExperimentButton.setGeometry(QtCore.QRect(150, 410, 300, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ExperimentButton.setFont(font)
        self.ExperimentButton.setObjectName("ExperimentButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.TitleLabel.setText(_translate("Form", "ViMMS Visualised"))
        self.SubHeadingLabel.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; font-style:italic;\">Vi</span><span style=\" font-style:italic;\">rtual</span><span style=\" font-weight:600; font-style:italic;\"> M</span><span style=\" font-style:italic;\">etabolomics</span><span style=\" font-weight:600; font-style:italic;\"> M</span><span style=\" font-style:italic;\">ass</span><span style=\" font-weight:600; font-style:italic;\"> S</span><span style=\" font-style:italic;\">pectrometer</span></p></body></html>"))
        self.ExtractGenerateButton.setText(_translate("Form", "Extract/Generate Data"))
        self.SimulateButton.setText(_translate("Form", "Simulate Experiment"))
        self.VisualiseButton.setText(_translate("Form", "Visualise Results"))
        self.ExperimentButton.setText(_translate("Form", "Perform Experiment"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
