# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VisualisePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VisualiseForm(object):
    def setupUi(self, VisualiseForm):
        VisualiseForm.setObjectName("VisualiseForm")
        VisualiseForm.resize(600, 500)
        self.VisualiseTitleLabel = QtWidgets.QLabel(VisualiseForm)
        self.VisualiseTitleLabel.setGeometry(QtCore.QRect(0, 0, 600, 100))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.VisualiseTitleLabel.setFont(font)
        self.VisualiseTitleLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.VisualiseTitleLabel.setObjectName("VisualiseTitleLabel")
        self.InteractAnimationTab = QtWidgets.QTabWidget(VisualiseForm)
        self.InteractAnimationTab.setGeometry(QtCore.QRect(0, 149, 600, 351))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InteractAnimationTab.sizePolicy().hasHeightForWidth())
        self.InteractAnimationTab.setSizePolicy(sizePolicy)
        self.InteractAnimationTab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.InteractAnimationTab.setIconSize(QtCore.QSize(16, 16))
        self.InteractAnimationTab.setObjectName("InteractAnimationTab")
        self.InteractTab = QtWidgets.QWidget()
        self.InteractTab.setObjectName("InteractTab")
        self.InteractAnimationTab.addTab(self.InteractTab, "")
        self.AnimationTab = QtWidgets.QWidget()
        self.AnimationTab.setObjectName("AnimationTab")
        self.InteractAnimationTab.addTab(self.AnimationTab, "")
        self.VisualiseHomeButton = QtWidgets.QPushButton(VisualiseForm)
        self.VisualiseHomeButton.setGeometry(QtCore.QRect(540, 20, 50, 50))
        self.VisualiseHomeButton.setText("")
        self.VisualiseHomeButton.setObjectName("VisualiseHomeButton")
        self.SelectFileDesc = QtWidgets.QLabel(VisualiseForm)
        self.SelectFileDesc.setGeometry(QtCore.QRect(0, 110, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SelectFileDesc.setFont(font)
        self.SelectFileDesc.setObjectName("SelectFileDesc")
        self.SelectFileButton = QtWidgets.QToolButton(VisualiseForm)
        self.SelectFileButton.setGeometry(QtCore.QRect(200, 110, 23, 20))
        self.SelectFileButton.setObjectName("SelectFileButton")
        self.RTRangeLabel = QtWidgets.QLabel(VisualiseForm)
        self.RTRangeLabel.setGeometry(QtCore.QRect(230, 110, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RTRangeLabel.setFont(font)
        self.RTRangeLabel.setObjectName("RTRangeLabel")
        self.RTMinTextEdit = QtWidgets.QLineEdit(VisualiseForm)
        self.RTMinTextEdit.setGeometry(QtCore.QRect(310, 110, 60, 20))
        self.RTMinTextEdit.setObjectName("RTMinTextEdit")
        self.RTMaxTextEdit = QtWidgets.QLineEdit(VisualiseForm)
        self.RTMaxTextEdit.setGeometry(QtCore.QRect(390, 110, 60, 20))
        self.RTMaxTextEdit.setObjectName("RTMaxTextEdit")
        self.RTRangeDashLabel = QtWidgets.QLabel(VisualiseForm)
        self.RTRangeDashLabel.setGeometry(QtCore.QRect(370, 110, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RTRangeDashLabel.setFont(font)
        self.RTRangeDashLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.RTRangeDashLabel.setObjectName("RTRangeDashLabel")
        self.VisualiseButton = QtWidgets.QPushButton(VisualiseForm)
        self.VisualiseButton.setGeometry(QtCore.QRect(480, 100, 111, 41))
        self.VisualiseButton.setObjectName("VisualiseButton")
        self.FileNameLabel = QtWidgets.QLabel(VisualiseForm)
        self.FileNameLabel.setGeometry(QtCore.QRect(0, 130, 221, 16))
        self.FileNameLabel.setObjectName("FileNameLabel")

        self.retranslateUi(VisualiseForm)
        self.InteractAnimationTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(VisualiseForm)

    def retranslateUi(self, VisualiseForm):
        _translate = QtCore.QCoreApplication.translate
        VisualiseForm.setWindowTitle(_translate("VisualiseForm", "Form"))
        self.VisualiseTitleLabel.setText(_translate("VisualiseForm", "Visualise Results"))
        self.InteractAnimationTab.setTabText(self.InteractAnimationTab.indexOf(self.InteractTab), _translate("VisualiseForm", "Interact"))
        self.InteractAnimationTab.setTabText(self.InteractAnimationTab.indexOf(self.AnimationTab), _translate("VisualiseForm", "Animation"))
        self.SelectFileDesc.setText(_translate("VisualiseForm", "Please Select an .mzML file:"))
        self.SelectFileButton.setText(_translate("VisualiseForm", "..."))
        self.RTRangeLabel.setText(_translate("VisualiseForm", "RT Range:"))
        self.RTRangeDashLabel.setText(_translate("VisualiseForm", "-"))
        self.VisualiseButton.setText(_translate("VisualiseForm", "Visualise"))
        self.FileNameLabel.setText(_translate("VisualiseForm", "No file selected."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VisualiseForm = QtWidgets.QWidget()
    ui = Ui_VisualiseForm()
    ui.setupUi(VisualiseForm)
    VisualiseForm.show()
    sys.exit(app.exec_())
