# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VisualisePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VisualiseForm(object):
    def setupUi(self, VisualiseForm):
        VisualiseForm.setObjectName("VisualiseForm")
        VisualiseForm.resize(600, 500)
        self.VisualiseTitleLabel = QtWidgets.QLabel(VisualiseForm)
        self.VisualiseTitleLabel.setGeometry(QtCore.QRect(0, 0, 600, 100))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.VisualiseTitleLabel.setFont(font)
        self.VisualiseTitleLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.VisualiseTitleLabel.setObjectName("VisualiseTitleLabel")
        self.VisualiseHomeButton = QtWidgets.QPushButton(VisualiseForm)
        self.VisualiseHomeButton.setGeometry(QtCore.QRect(540, 20, 50, 50))
        self.VisualiseHomeButton.setText("")
        self.VisualiseHomeButton.setObjectName("VisualiseHomeButton")
        self.SelectFileDesc = QtWidgets.QLabel(VisualiseForm)
        self.SelectFileDesc.setGeometry(QtCore.QRect(10, 110, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SelectFileDesc.setFont(font)
        self.SelectFileDesc.setObjectName("SelectFileDesc")
        self.RTRangeLabel = QtWidgets.QLabel(VisualiseForm)
        self.RTRangeLabel.setGeometry(QtCore.QRect(305, 110, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RTRangeLabel.setFont(font)
        self.RTRangeLabel.setObjectName("RTRangeLabel")
        self.RTMinTextEdit = QtWidgets.QLineEdit(VisualiseForm)
        self.RTMinTextEdit.setGeometry(QtCore.QRect(335, 110, 60, 20))
        self.RTMinTextEdit.setObjectName("RTMinTextEdit")
        self.RTMaxTextEdit = QtWidgets.QLineEdit(VisualiseForm)
        self.RTMaxTextEdit.setGeometry(QtCore.QRect(415, 110, 60, 20))
        self.RTMaxTextEdit.setObjectName("RTMaxTextEdit")
        self.RTRangeDashLabel = QtWidgets.QLabel(VisualiseForm)
        self.RTRangeDashLabel.setGeometry(QtCore.QRect(395, 110, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RTRangeDashLabel.setFont(font)
        self.RTRangeDashLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.RTRangeDashLabel.setObjectName("RTRangeDashLabel")
        self.VisualiseButton = QtWidgets.QPushButton(VisualiseForm)
        self.VisualiseButton.setEnabled(False)
        self.VisualiseButton.setGeometry(QtCore.QRect(480, 100, 111, 41))
        self.VisualiseButton.setObjectName("VisualiseButton")
        self.GraphTypeComboBox = QtWidgets.QComboBox(VisualiseForm)
        self.GraphTypeComboBox.setGeometry(QtCore.QRect(10, 145, 221, 22))
        self.GraphTypeComboBox.setObjectName("GraphTypeComboBox")
        self.GraphTypeComboBox.addItem("")
        self.GraphTypeComboBox.addItem("")
        self.CanvasGroupBox = QtWidgets.QGroupBox(VisualiseForm)
        self.CanvasGroupBox.setGeometry(QtCore.QRect(100, 180, 400, 321))
        self.CanvasGroupBox.setTitle("")
        self.CanvasGroupBox.setObjectName("CanvasGroupBox")
        self.MzmlUploadGroupBox = QtWidgets.QGroupBox(VisualiseForm)
        self.MzmlUploadGroupBox.setGeometry(QtCore.QRect(210, 100, 71, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MzmlUploadGroupBox.sizePolicy().hasHeightForWidth())
        self.MzmlUploadGroupBox.setSizePolicy(sizePolicy)
        self.MzmlUploadGroupBox.setStyleSheet("padding: 0; \n"
"background-color: rgb(240, 240, 240);")
        self.MzmlUploadGroupBox.setTitle("")
        self.MzmlUploadGroupBox.setObjectName("MzmlUploadGroupBox")

        self.retranslateUi(VisualiseForm)
        QtCore.QMetaObject.connectSlotsByName(VisualiseForm)

    def retranslateUi(self, VisualiseForm):
        _translate = QtCore.QCoreApplication.translate
        VisualiseForm.setWindowTitle(_translate("VisualiseForm", "Form"))
        self.VisualiseTitleLabel.setText(_translate("VisualiseForm", "Visualise Results"))
        self.SelectFileDesc.setText(_translate("VisualiseForm", "Please Select an .mzML file:"))
        self.RTRangeLabel.setText(_translate("VisualiseForm", "RT:"))
        self.RTRangeDashLabel.setText(_translate("VisualiseForm", "-"))
        self.VisualiseButton.setText(_translate("VisualiseForm", "Visualise"))
        self.GraphTypeComboBox.setItemText(0, _translate("VisualiseForm", "Scatter Plot"))
        self.GraphTypeComboBox.setItemText(1, _translate("VisualiseForm", "3d Bar Plot"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VisualiseForm = QtWidgets.QWidget()
    ui = Ui_VisualiseForm()
    ui.setupUi(VisualiseForm)
    VisualiseForm.show()
    sys.exit(app.exec_())
